kind: pipeline
name: default
steps:
- name: build
  image: ubuntu:trusty
  commands:
   - apt update
   - apt install docker-ce kpartx qemu-user-static aria2 tree python-requests
   - service docker stop && rm -rf /var/lib/docker && service docker start
   - mkdir images && PATH=./node_modules/.bin:$PATH ./builder --noninteractive
